# Generated by Django 3.2.7 on 2021-09-17 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=64)),
                ('semester', models.PositiveIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('limit_seat', models.PositiveIntegerField()),
                ('siting', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
                ('student', models.ManyToManyField(blank=True, related_name='enroll', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
